language: node_js

node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

before_script:
  - npm prune

script:
  - npm run validate-commits
  - npm run prepublishOnly

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
